config/routes.rb
Weather::Application.routes.draw do
  get "humidities/index"
  get "humidities/show"
  get "temperatures/index"
  get "temperatures/show"
  get "rainfalls/index"
  get "rainfalls/show"
  get "sensors/index"
  get "sensors/show"
  get "winds/index"
  get "winds/show"
  get "welcome/index"
  post "welcome/index"
  
  resources :charts do
    collection do
      get 'basic_line'
      get 'line_ajax'
      get 'line_labels'
    end
  end

  resources :sensors  
  resources :temperatures
  resources :humidities
  resources :winds
  resources :rainfalls

  root :to => 'welcome#index'

end

app/models/rainfall.rb
class Rainfall < ActiveRecord::Base
  self.table_name = "Rainfall"
  belongs_to :sensor, :foreign_key => 'sensor'
	
  	def self.display_data(page, sort)
		self.paginate(:page => page,
				  :per_page => 10,
				  :order => sort.nil? ? self.primary_key : sort)
		#can also include :joins and :conditions
	end
	
	def HexColour
		begin
			sensor.Identifier == 1 ? 'FF7777' : '7777FF'
		rescue
			'D0D0D0'
		end
	end

	def DullHexColour
		begin
			sensor.Identifier == 1 ? 'FFBBBB' : 'BBBBFF'
		rescue
			'B0B0B0'
		end
	end

end

app/controllers/rainfalls_controller.rb
class RainfallsController < ApplicationController

def show
  @rainfall = Rainfall.find(params[:id])
end

def index
  params[:sort_by] = 'Identifier desc'
  @rainfalls = Rainfall.display_data(params[:page], params[:sort_by])
end

end

app/helpers/rainfalls_helper.rb
module RainfallsHelper
end

app/views/rainfalls/index.html.erb
<h1>Listing rainfalls</h1>

<table>
  <thead>
  <tr>
    <th width="100" align="left">Sensor</th>
    <th width="120" align="left">From</th>
    <th width="120" align="left">To</th>
    <th width="100" align="left">Value</th>
    <th></th>
  </tr>
  </thead>
  
  <tbody>
  <% @rainfalls.each do |rainfall| %>
    <tr bgcolor="<%= cycle(rainfall.HexColour,rainfall.DullHexColour)%>">
      <td><%=h rainfall.sensor.Name %></td>
      <td><%=h rainfall.fromDttm.strftime("%d %b %H:%M") %></td>
      <td><%=h rainfall.toDttm.strftime("%d %b %H:%M") %></td>
      <td><%=h rainfall.value %></td>
      <td bgcolor="FFFFFF"><%= link_to 'Show', rainfall_path(rainfall) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @rainfalls %>
<%= link_to 'New rainfall', new_rainfall_path %>

app/views/rainfalls/show.html.erb
<h1>Rainfalls#show</h1>
<p>Find me in app/views/rainfalls/show.html.erb</p>