config/routes.rb
Weather::Application.routes.draw do
  get "humidities/index"
  get "humidities/show"
  get "temperatures/index"
  get "temperatures/show"
  get "rainfalls/index"
  get "rainfalls/show"
  get "sensors/index"
  get "sensors/show"
  get "winds/index"
  get "winds/show"
  get "welcome/index"
  post "welcome/index"
  
  resources :charts do
    collection do
      get 'basic_line'
      get 'line_ajax'
      get 'line_labels'
    end
  end

  resources :sensors  
  resources :temperatures
  resources :humidities
  resources :winds
  resources :rainfalls

  root :to => 'welcome#index'

end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
	self.table_name = "Sensor"
	
  	def self.display_data(page, sort)
		self.paginate(:page => page,
				  :per_page => 10,
				  :order => sort.nil? ? self.primary_key : sort)
		#can also include :joins and :conditions
	end
	
	def HexColour
		begin
			self.Identifier == 1 ? 'FF7777' : '7777FF'
		rescue
			'D0D0D0'
		end
	end

	def DullHexColour
		begin
			self.Identifier == 1 ? 'FFBBBB' : 'BBBBFF'
		rescue
			'B0B0B0'
		end
	end

end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController

def show
  @sensor = Sensor.find(params[:id])
end

def index
  @sensors = Sensor.display_data(params[:page], params[:sort_by])
end

end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/sensors/index.html.erb
<h1>Listing sensors</h1>

<table>
  <thead>
  <tr>
    <th width="100" align="left">Name</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @sensors.each do |sensor| %>
    <tr bgcolor="<%= cycle(sensor.HexColour,sensor.DullHexColour)%>">
      <td><%=h sensor.Name %></td>
      <td bgcolor="FFFFFF"><%= link_to 'Show', sensor_path(sensor) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @sensors %>
<%= link_to 'New sensor', new_sensor_path %>

app/views/sensors/show.html.erb
<h1>Sensors#show</h1>
<p>Find me in app/views/sensors/show.html.erb</p>