config/routes.rb
Weather::Application.routes.draw do
  get "humidities/index"
  get "humidities/show"
  get "temperatures/index"
  get "temperatures/show"
  get "rainfalls/index"
  get "rainfalls/show"
  get "sensors/index"
  get "sensors/show"
  get "winds/index"
  get "winds/show"
  get "welcome/index"
  post "welcome/index"
  
  resources :charts do
    collection do
      get 'basic_line'
      get 'line_ajax'
      get 'line_labels'
    end
  end

  resources :sensors  
  resources :temperatures
  resources :humidities
  resources :winds
  resources :rainfalls

  root :to => 'welcome#index'

end

app/models/wind.rb
class Wind < ActiveRecord::Base
  self.table_name = "Wind"
  belongs_to :sensor, :foreign_key => 'sensor'
	
  	def self.display_data(page, sort)
		self.paginate(:page => page,
				  :per_page => 10,
				  :order => sort.nil? ? self.primary_key : sort)
		#can also include :joins and :conditions
	end
	
	def HexColour
		begin
			sensor.Identifier == 1 ? 'FF7777' : '7777FF'
		rescue
			'D0D0D0'
		end
	end

	def DullHexColour
		begin
			sensor.Identifier == 1 ? 'FFBBBB' : 'BBBBFF'
		rescue
			'B0B0B0'
		end
	end

end

app/controllers/winds_controller.rb
class WindsController < ApplicationController

def show
  @wind = Wind.find(params[:id])
end

def index
  params[:sort_by] = 'Identifier desc'
  @winds = Wind.display_data(params[:page], params[:sort_by])
end

end

app/helpers/winds_helper.rb
module WindsHelper
end

app/views/winds/index.html.erb
<h1>Listing winds</h1>

<table>
  <thead>
  <tr>
    <th width="100" align="left">Sensor</th>
    <th width="120" align="left">From</th>
    <th width="120" align="left">To</th>
    <th width="100" align="left">Direction</th>
    <th width="100" align="left">Speed</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @winds.each do |wind| %>
    <tr bgcolor="<%= cycle(wind.HexColour,wind.DullHexColour)%>">
      <td><%=h wind.sensor.Name %></td>
      <td><%=h wind.fromDttm.strftime("%d %b %H:%M") %></td>
      <td><%=h wind.toDttm.strftime("%d %b %H:%M") %></td>
      <td><%=h wind.direction %></td>
      <td><%=h wind.speed %></td>
      <td bgcolor="FFFFFF"><%= link_to 'Show', wind_path(wind) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @winds %>
<%= link_to 'New wind', new_wind_path %>

app/views/winds/show.html.erb
<h1>Winds#show</h1>
<p>Find me in app/views/winds/show.html.erb</p>