config/routes.rb
Weather::Application.routes.draw do
  get "humidities/index"
  get "humidities/show"
  get "temperatures/index"
  get "temperatures/show"
  get "rainfalls/index"
  get "rainfalls/show"
  get "sensors/index"
  get "sensors/show"
  get "winds/index"
  get "winds/show"
  get "welcome/index"
  post "welcome/index"
  
  resources :charts do
    collection do
      get 'basic_line'
      get 'line_ajax'
      get 'line_labels'
    end
  end

  resources :sensors  
  resources :temperatures
  resources :humidities
  resources :winds
  resources :rainfalls

  root :to => 'welcome#index'

end

app/models/humidity.rb
class Humidity < ActiveRecord::Base
  self.table_name = "Humidity"
  belongs_to :sensor, :foreign_key => 'sensor'
	
  	def self.display_data(page, sort)
		self.paginate(:page => page,
				  :per_page => 10,
				  :order => sort.nil? ? self.primary_key : sort)
		#can also include :joins and :conditions
	end
	
	def HexColour
		begin
			sensor.Identifier == 1 ? 'FF7777' : '7777FF'
		rescue
			'D0D0D0'
		end
	end

	def DullHexColour
		begin
			sensor.Identifier == 1 ? 'FFBBBB' : 'BBBBFF'
		rescue
			'B0B0B0'
		end
	end

end

app/controllers/humidities_controller.rb
class HumiditiesController < ApplicationController

def show
  @humidity = Humidity.find(params[:id])
end

def index
  params[:sort_by] = 'Identifier desc'
  @humidities = Humidity.display_data(params[:page], params[:sort_by])
end

end

app/helpers/humidities_helper.rb
module HumiditiesHelper
end

app/views/humidities/index.html.erb
<h1>Listing humidities</h1>

<table>
  <thead>
  <tr>
    <th width="100" align="left">Sensor</th>
    <th width="120" align="left">From</th>
    <th width="120" align="left">To</th>
    <th width="100" align="left">Value</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @humidities.each do |humidity| %>
    <tr bgcolor="<%= cycle(humidity.HexColour,humidity.DullHexColour)%>">
      <td><%=h humidity.sensor.Name %></td>
      <td><%=h humidity.fromDttm.strftime("%d %b %H:%M") %></td>
      <td><%=h humidity.toDttm.strftime("%d %b %H:%M") %></td>
      <td><%=h humidity.value %></td>
      <td bgcolor="FFFFFF"><%= link_to 'Show', humidity_path(humidity) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @humidities %>
<%= link_to 'New humidity', new_humidity_path %>

app/views/humidities/show.html.erb
<h1>Humidities#show</h1>
<p>Find me in app/views/humidities/show.html.erb</p>